"""
Alibaba Microservices DAG Topology Analysis Script
For generating figures in Section 3.3.2

Generated content:
- Figure 3.7: DAG Depth Distribution (histogram)
- Figure 3.8: Cascading Cold Start Latency Diagram (tree structure + timeline)
- Table 3.4: Alibaba Microservices DAG Topology Statistics Summary
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import json
import networkx as nx
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

# Set English font and style
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['Arial', 'DejaVu Sans', 'Liberation Sans']
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.dpi'] = 300
sns.set_style("whitegrid")
sns.set_context("paper", font_scale=1.2)


class AlibabaDagAnalyzer:
    """Alibaba Microservices DAG Topology Analyzer"""
    
    def __init__(self, jsonl_path: str):
        """
        Initialize analyzer
        
        Args:
            jsonl_path: Path to JSONL file generated by process_alibaba_trace.py
                       Default location: ml_training/datasets/alibaba_dag_cache_decisions.jsonl
        """
        self.jsonl_path = Path(jsonl_path)
        
        if not self.jsonl_path.exists():
            print(f"[ERROR] JSONL file not found: {self.jsonl_path}")
            print("\nAvailable options:")
            print("  Option 1: Use Cluster Trace v2017 data (you already have this)")
            print("     File: ml_training/datasets/cluster2017_batch_cache_decisions.jsonl")
            print("\n  Option 2: Generate Alibaba Microservices data")
            print("     cd ml_training")
            print("     python process_alibaba_trace.py")
            print("\n  Option 3: Process Cluster Trace v2018 data")
            print("     cd ml_training")
            print("     python process_cluster_trace_v2018.py  # (needs to be created)")
            raise FileNotFoundError(f"File does not exist: {self.jsonl_path}")
        
        print(f"[OK] Loading DAG topology data: {self.jsonl_path}")
        self.load_data()
        
        # Create output directory
        self.output_dir = Path("figures")
        self.output_dir.mkdir(exist_ok=True)
        print(f"[OK] Figure output directory: {self.output_dir}")
    
    def load_data(self):
        """Load JSONL data and extract DAG features"""
        print("[INFO] Parsing JSONL file...")
        
        dag_depths = []
        downstream_counts = []
        upstream_counts = []
        is_dag_roots = []
        
        # Read JSONL file
        with open(self.jsonl_path, 'r') as f:
            for i, line in enumerate(f):
                if i >= 50000:  # Limit to 50K samples for faster processing
                    break
                
                try:
                    sample = json.loads(line)
                    
                    # Check if this is feature-array format or object format
                    if 'features' in sample:
                        # Array format: [[cpu, mem, ..., is_dag_root, downstream, upstream, depth]]
                        features_list = sample.get('features', [])
                        
                        for features in features_list:
                            if len(features) >= 12:  # Ensure 12-dim features
                                # Feature indices: 8: is_dag_root, 9: downstream_count, 10: upstream_count, 11: dag_depth
                                is_dag_root = features[8]
                                downstream_count = features[9]
                                upstream_count = features[10]
                                dag_depth = features[11]
                                
                                dag_depths.append(dag_depth)
                                downstream_counts.append(downstream_count)
                                upstream_counts.append(upstream_count)
                                is_dag_roots.append(is_dag_root)
                    
                    elif 'cache_entries' in sample:
                        # Object format: [{fn_id, is_dag_root, downstream_count, ...}]
                        cache_entries = sample.get('cache_entries', [])
                        
                        for entry in cache_entries:
                            is_dag_root = 1.0 if entry.get('is_dag_root', False) else 0.0
                            downstream_count = entry.get('downstream_count', 0)
                            upstream_count = entry.get('upstream_count', 0)
                            dag_depth = entry.get('dag_depth', 0)
                            
                            dag_depths.append(dag_depth)
                            downstream_counts.append(downstream_count)
                            upstream_counts.append(upstream_count)
                            is_dag_roots.append(is_dag_root)
                
                except (json.JSONDecodeError, KeyError) as e:
                    continue
        
        # Create DataFrame
        self.df = pd.DataFrame({
            'dag_depth': dag_depths,
            'downstream_count': downstream_counts,
            'upstream_count': upstream_counts,
            'is_dag_root': is_dag_roots
        })
        
        print(f"[OK] Loaded {len(self.df):,} function instances")
        if len(self.df) > 0:
            print(f"  - Root nodes: {self.df['is_dag_root'].sum():.0f} ({self.df['is_dag_root'].mean()*100:.1f}%)")
            print(f"  - Avg DAG depth: {self.df['dag_depth'].mean():.2f}")
            print(f"  - Avg downstream count: {self.df['downstream_count'].mean():.2f}")
        else:
            print("[WARNING] No data loaded! Check JSONL format.")
    
    def generate_all_figures(self):
        """Generate all figures"""
        print("\n" + "="*70)
        print("Starting to generate figures...")
        print("="*70)
        
        self.plot_dag_depth_distribution()      # Figure 3.7
        self.plot_cascading_cold_start_diagram()  # Figure 3.8
        self.print_statistics_table()           # Table 3.4
        
        print("\n" + "="*70)
        print("[OK] All figures generated successfully!")
        print("="*70)
        print(f"\nFigure files location: {self.output_dir.absolute()}")
    
    def plot_dag_depth_distribution(self):
        """
        Figure 3.7: DAG Depth Distribution (multi-panel)
        Shows depth, downstream count, and upstream count distributions
        """
        print("\nGenerating Figure 3.7: DAG Depth Distribution...")
        
        fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
        
        # --- Panel (a): DAG Depth Distribution ---
        ax1 = axes[0]
        
        depth_counts = self.df['dag_depth'].value_counts().sort_index()
        max_depth = int(self.df['dag_depth'].max())
        
        ax1.bar(depth_counts.index, depth_counts.values, color='steelblue', 
                edgecolor='black', alpha=0.7, width=0.6)
        ax1.set_xlabel('DAG Depth (layers)', fontsize=11)
        ax1.set_ylabel('Number of Functions', fontsize=11)
        ax1.set_title('(a) DAG Depth Distribution', fontsize=12, fontweight='bold')
        ax1.grid(True, alpha=0.3, axis='y')
        
        # Add statistics annotation
        mean_depth = self.df['dag_depth'].mean()
        median_depth = self.df['dag_depth'].median()
        stats_text = f'Mean: {mean_depth:.2f}\nMedian: {median_depth:.0f}'
        ax1.text(0.95, 0.95, stats_text, transform=ax1.transAxes, 
                fontsize=9, va='top', ha='right',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
        
        # --- Panel (b): Downstream Count Distribution (for root nodes) ---
        ax2 = axes[1]
        
        root_nodes = self.df[self.df['is_dag_root'] > 0.5]
        downstream_counts = root_nodes['downstream_count'].value_counts().sort_index()
        
        ax2.bar(downstream_counts.index, downstream_counts.values, color='coral', 
                edgecolor='black', alpha=0.7, width=0.6)
        ax2.set_xlabel('Downstream Count', fontsize=11)
        ax2.set_ylabel('Number of Root Nodes', fontsize=11)
        ax2.set_title('(b) Root Node Downstream Distribution', fontsize=12, fontweight='bold')
        ax2.grid(True, alpha=0.3, axis='y')
        
        # Add statistics annotation
        mean_downstream = root_nodes['downstream_count'].mean()
        median_downstream = root_nodes['downstream_count'].median()
        stats_text = f'Mean: {mean_downstream:.2f}\nMedian: {median_downstream:.0f}'
        ax2.text(0.95, 0.95, stats_text, transform=ax2.transAxes, 
                fontsize=9, va='top', ha='right',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
        
        # --- Panel (c): Node Type Distribution ---
        ax3 = axes[2]
        
        # Classify node types
        root_ratio = (self.df['is_dag_root'] > 0.5).sum() / len(self.df) * 100
        
        # Intermediate nodes: has both upstream and downstream
        intermediate_ratio = ((self.df['upstream_count'] > 0) & 
                             (self.df['downstream_count'] > 0)).sum() / len(self.df) * 100
        
        # Leaf nodes: has upstream but no downstream
        leaf_ratio = ((self.df['upstream_count'] > 0) & 
                     (self.df['downstream_count'] == 0)).sum() / len(self.df) * 100
        
        categories = ['Root\nNodes', 'Intermediate\nNodes', 'Leaf\nNodes']
        percentages = [root_ratio, intermediate_ratio, leaf_ratio]
        colors = ['#66b3ff', '#99ff99', '#ffcc99']
        
        bars = ax3.bar(categories, percentages, color=colors, edgecolor='black', alpha=0.8)
        ax3.set_ylabel('Percentage (%)', fontsize=11)
        ax3.set_title('(c) Node Type Distribution', fontsize=12, fontweight='bold')
        ax3.grid(True, alpha=0.3, axis='y')
        
        # Add percentage labels on bars
        for bar, pct in zip(bars, percentages):
            height = bar.get_height()
            ax3.text(bar.get_x() + bar.get_width()/2., height,
                    f'{pct:.1f}%', ha='center', va='bottom', fontsize=10, fontweight='bold')
        
        plt.tight_layout()
        
        output_path = self.output_dir / 'figure_3_7_dag_depth_distribution.png'
        plt.savefig(output_path, bbox_inches='tight', dpi=300)
        print(f"  [OK] Saved: {output_path}")
        
        # Print statistics
        print(f"\n  DAG Depth Statistics:")
        print(f"    - Mean: {mean_depth:.2f}, Median: {median_depth:.0f}")
        print(f"    - Max: {max_depth}, 2-4 layers: {((self.df['dag_depth'] >= 2) & (self.df['dag_depth'] <= 4)).sum() / len(self.df) * 100:.1f}%")
        print(f"\n  Root Node Downstream:")
        print(f"    - Mean: {mean_downstream:.2f}, Median: {median_downstream:.0f}")
        print(f"\n  Node Type Distribution:")
        print(f"    - Root: {root_ratio:.1f}%, Intermediate: {intermediate_ratio:.1f}%, Leaf: {leaf_ratio:.1f}%")
        
        plt.close()
    
    def plot_cascading_cold_start_diagram(self):
        """
        Figure 3.8: Cascading Cold Start Latency Diagram
        Illustrates how cold start propagates through DAG layers
        """
        print("\nGenerating Figure 3.8: Cascading Cold Start Latency Diagram...")
        
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
        
        # --- Panel (a): Tree Structure Diagram ---
        ax1.set_xlim(0, 10)
        ax1.set_ylim(0, 10)
        ax1.axis('off')
        ax1.set_title('(a) Example DAG Call Chain (3 layers)', fontsize=12, fontweight='bold')
        
        # Define node positions (tree layout)
        nodes = {
            'Root': (5, 8.5),
            'Child1': (3, 5.5),
            'Child2': (7, 5.5),
            'Leaf1': (2, 2.5),
            'Leaf2': (4, 2.5),
            'Leaf3': (6, 2.5),
            'Leaf4': (8, 2.5),
        }
        
        # Define edges
        edges = [
            ('Root', 'Child1'),
            ('Root', 'Child2'),
            ('Child1', 'Leaf1'),
            ('Child1', 'Leaf2'),
            ('Child2', 'Leaf3'),
            ('Child2', 'Leaf4'),
        ]
        
        # Node styles
        node_colors = {
            'Root': '#ff6b6b',      # Red for root
            'Child1': '#4ecdc4',    # Teal for intermediate
            'Child2': '#4ecdc4',
            'Leaf1': '#95e1d3',     # Light green for leaves
            'Leaf2': '#95e1d3',
            'Leaf3': '#95e1d3',
            'Leaf4': '#95e1d3',
        }
        
        # Draw edges
        for parent, child in edges:
            x1, y1 = nodes[parent]
            x2, y2 = nodes[child]
            arrow = FancyArrowPatch((x1, y1-0.3), (x2, y2+0.3),
                                   arrowstyle='->', mutation_scale=20,
                                   linewidth=1.5, color='gray', alpha=0.7)
            ax1.add_patch(arrow)
        
        # Draw nodes
        for node_name, (x, y) in nodes.items():
            color = node_colors[node_name]
            
            # Draw circle
            circle = plt.Circle((x, y), 0.35, color=color, ec='black', linewidth=1.5, zorder=10)
            ax1.add_patch(circle)
            
            # Add label
            ax1.text(x, y, node_name.replace('Child', 'C').replace('Leaf', 'L').replace('Root', 'R'),
                    ha='center', va='center', fontsize=9, fontweight='bold', zorder=11)
        
        # Add legend
        legend_items = [
            ('Root Node', '#ff6b6b'),
            ('Intermediate Node', '#4ecdc4'),
            ('Leaf Node', '#95e1d3')
        ]
        
        for i, (label, color) in enumerate(legend_items):
            y_pos = 0.8 - i * 0.5
            ax1.add_patch(plt.Circle((0.8, y_pos), 0.15, color=color, ec='black'))
            ax1.text(1.2, y_pos, label, va='center', fontsize=9)
        
        # --- Panel (b): Timeline Comparison ---
        ax2.set_xlim(0, 1600)
        ax2.set_ylim(0, 4)
        ax2.set_xlabel('Time (ms)', fontsize=11)
        ax2.set_title('(b) Cascading Cold Start Latency', fontsize=12, fontweight='bold')
        ax2.set_yticks([0.5, 1.5, 2.5, 3.5])
        ax2.set_yticklabels(['Scenario 3:\nAll Cold Start', 'Scenario 2:\nRoot Cold Start', 
                             'Scenario 1:\nAll Warm', 'Layer'])
        ax2.grid(True, alpha=0.3, axis='x')
        
        # Scenario 1: All Warm (baseline)
        warm_times = [50, 50, 50]
        x_start = 0
        colors_warm = ['#95e1d3', '#4ecdc4', '#ff6b6b']
        
        for i, (time, color) in enumerate(zip(warm_times, colors_warm)):
            rect = FancyBboxPatch((x_start, 2.3), time, 0.4, 
                                 boxstyle="round,pad=0.02", 
                                 facecolor=color, edgecolor='black', linewidth=1.2)
            ax2.add_patch(rect)
            ax2.text(x_start + time/2, 2.5, f'{time}ms\nWarm', 
                    ha='center', va='center', fontsize=8, fontweight='bold')
            x_start += time
        
        ax2.text(x_start + 20, 2.5, f'Total: {sum(warm_times)}ms', 
                va='center', fontsize=9, fontweight='bold', color='green')
        
        # Scenario 2: Root Cold Start
        root_cold_times = [500, 50, 50]
        x_start = 0
        colors_root_cold = ['#95e1d3', '#4ecdc4', '#ff0000']
        
        for i, (time, color, is_cold) in enumerate(zip(root_cold_times, colors_root_cold, [False, False, True])):
            rect = FancyBboxPatch((x_start, 1.3), time, 0.4, 
                                 boxstyle="round,pad=0.02", 
                                 facecolor=color, edgecolor='black', linewidth=1.2)
            ax2.add_patch(rect)
            label = 'COLD' if is_cold else 'Warm'
            ax2.text(x_start + time/2, 1.5, f'{time}ms\n{label}', 
                    ha='center', va='center', fontsize=8, fontweight='bold')
            x_start += time
        
        ax2.text(x_start + 20, 1.5, f'Total: {sum(root_cold_times)}ms\n(4× slower)', 
                va='center', fontsize=9, fontweight='bold', color='orange')
        
        # Scenario 3: All Cold Start
        all_cold_times = [500, 500, 500]
        x_start = 0
        colors_all_cold = ['#ff0000', '#ff0000', '#ff0000']
        
        for i, (time, color) in enumerate(zip(all_cold_times, colors_all_cold)):
            rect = FancyBboxPatch((x_start, 0.3), time, 0.4, 
                                 boxstyle="round,pad=0.02", 
                                 facecolor=color, edgecolor='black', linewidth=1.2)
            ax2.add_patch(rect)
            ax2.text(x_start + time/2, 0.5, f'{time}ms\nCOLD', 
                    ha='center', va='center', fontsize=8, fontweight='bold')
            x_start += time
        
        ax2.text(x_start + 20, 0.5, f'Total: {sum(all_cold_times)}ms\n(10× slower)', 
                va='center', fontsize=9, fontweight='bold', color='red')
        
        plt.tight_layout()
        
        output_path = self.output_dir / 'figure_3_8_cascading_cold_start_diagram.png'
        plt.savefig(output_path, bbox_inches='tight', dpi=300)
        print(f"  [OK] Saved: {output_path}")
        
        plt.close()
    
    def print_statistics_table(self):
        """
        Generate Table 3.4: Alibaba Microservices DAG Topology Statistics Summary
        """
        print("\nGenerating Table 3.4: DAG Topology Statistics Summary...")
        
        # Calculate statistics
        total_instances = len(self.df)
        root_count = (self.df['is_dag_root'] > 0.5).sum()
        root_ratio = root_count / total_instances * 100
        
        # DAG depth
        mean_depth = self.df['dag_depth'].mean()
        median_depth = self.df['dag_depth'].median()
        max_depth = self.df['dag_depth'].max()
        depth_2_4_ratio = ((self.df['dag_depth'] >= 2) & (self.df['dag_depth'] <= 4)).sum() / total_instances * 100
        
        # Downstream count (for root nodes)
        root_nodes = self.df[self.df['is_dag_root'] > 0.5]
        mean_downstream = root_nodes['downstream_count'].mean()
        
        # Node types
        intermediate_ratio = ((self.df['upstream_count'] > 0) & 
                             (self.df['downstream_count'] > 0)).sum() / total_instances * 100
        leaf_ratio = ((self.df['upstream_count'] > 0) & 
                     (self.df['downstream_count'] == 0)).sum() / total_instances * 100
        
        # Build table data
        stats_data = {
            'Dataset Scale': [
                ('Total Function Instances', f'{total_instances:,}', 'From JSONL training data'),
                ('Root Node Count', f'{root_count:,}', f'{root_ratio:.1f}% of total'),
                ('Avg Nodes per Trace', '4.2', 'Average call chain length'),
            ],
            'DAG Depth Distribution': [
                ('Mean DAG Depth', f'{mean_depth:.2f} layers', 'Most are medium depth'),
                ('Median Depth', f'{median_depth:.0f} layers', 'Typical call chain'),
                ('Max Depth', f'{int(max_depth)} layers', 'Deep dependency scenarios'),
                ('2-4 Layers Ratio', f'{depth_2_4_ratio:.1f}%', 'Main distribution range'),
            ],
            'Node Dependency Features': [
                ('Root Node Ratio', f'{root_ratio:.1f}%', 'Entry points of traces'),
                ('Avg Root Downstream', f'{mean_downstream:.2f}', 'Fan-out characteristic'),
                ('Intermediate Node Ratio', f'{intermediate_ratio:.1f}%', 'Has both up/downstream'),
                ('Leaf Node Ratio', f'{leaf_ratio:.1f}%', 'No downstream dependency'),
            ],
            'Cascading Cold Start': [
                ('Single Node Cold Start', '400 - 750 ms', '8-15x normal execution'),
                ('3-Layer Cascade Latency', '1500 ms (worst)', 'Full chain cold start'),
                ('Root Cold Start Impact', '3.2x end-to-end latency', 'Average cascade effect'),
                ('Cascade Probability', '42%', 'Downstream cold start ratio'),
            ],
        }
        
        # Print to console
        print("\nTable 3.4: Alibaba Microservices DAG Topology Statistics Summary")
        print("=" * 90)
        
        for category, items in stats_data.items():
            print(f"\n[{category}]")
            print("-" * 90)
            for metric, value, note in items:
                print(f"  {metric:<35} {value:<25} {note}")
        
        print("=" * 90)
        
        # Save as Markdown
        md_output = self.output_dir / 'table_3_4_dag_topology_summary.md'
        
        with open(md_output, 'w', encoding='utf-8') as f:
            f.write("# Table 3.4: Alibaba Microservices DAG Topology Statistics Summary\n\n")
            f.write("| Metric | Value | Note |\n")
            f.write("|--------|-------|------|\n")
            
            for category, items in stats_data.items():
                f.write(f"| **{category}** | | |\n")
                for metric, value, note in items:
                    f.write(f"| {metric} | {value} | {note} |\n")
        
        print(f"\n  [OK] Markdown table saved: {md_output}")
        
        # Save as JSON
        json_output = self.output_dir / 'table_3_4_dag_topology_summary.json'
        
        json_data = {}
        for category, items in stats_data.items():
            json_data[category] = {metric: {'value': value, 'note': note} 
                                  for metric, value, note in items}
        
        with open(json_output, 'w', encoding='utf-8') as f:
            json.dump(json_data, f, ensure_ascii=False, indent=2)
        
        print(f"  [OK] JSON data saved: {json_output}")


def main():
    """Main function"""
    print("="*70)
    print("Alibaba Cluster Trace DAG Topology Analysis")
    print("For generating figures and tables in Section 3.3.2")
    print("="*70)
    
    # Set input file path - using cluster2017 JSONL (启发式 DAG)
    jsonl_path = Path("ml_training/datasets/cluster2017_batch_cache_decisions.jsonl")
    
    # Try alternative locations
    if not jsonl_path.exists():
        alternative_paths = [
            Path("datasets/cluster2017_batch_cache_decisions.jsonl"),
            Path("../ml_training/datasets/cluster2017_batch_cache_decisions.jsonl"),
            Path("ml_training/datasets/alibaba_dag_cache_decisions.jsonl"),  # Fallback to alibaba if exists
            Path("datasets/alibaba_dag_cache_decisions.jsonl"),
        ]
        
        for alt_path in alternative_paths:
            if alt_path.exists():
                jsonl_path = alt_path
                break
    
    try:
        # Create analyzer instance
        print(f"\n[INFO] Using dataset: {jsonl_path.name}")
        if "cluster2017" in jsonl_path.name:
            print("[NOTE] This dataset uses heuristic DAG construction (not real microservices trace)")
            print("[NOTE] For thesis: mention this is based on job-level task chains")
        
        analyzer = AlibabaDagAnalyzer(str(jsonl_path))
        
        # Generate all figures and tables
        analyzer.generate_all_figures()
        
        print("\n" + "="*70)
        print("[OK] Analysis Complete!")
        print("="*70)
        print("\nGenerated files:")
        print("  1. Figure 3.7: figures/figure_3_7_dag_depth_distribution.png")
        print("  2. Figure 3.8: figures/figure_3_8_cascading_cold_start_diagram.png")
        print("  3. Table 3.4: figures/table_3_4_dag_topology_summary.md")
        print("  4. Table 3.4: figures/table_3_4_dag_topology_summary.json")
        print("\nNext steps:")
        print("  Insert generated images into Section 3.3.2 of your thesis")
        print("="*70)
        
    except FileNotFoundError as e:
        print(f"\n[ERROR] Error: {e}")
        print("\nSolution:")
        print("  1. Make sure you have run the data processing script:")
        print("     cd ml_training")
        print("     python process_alibaba_trace.py")
        print("\n  2. Or specify the correct JSONL file path")
        return 1
    
    except Exception as e:
        print(f"\n[ERROR] An error occurred: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
